enum UserRole {
  ADMIN
  USER
}

type User {
  id: ID!
  name: String!
  email: String!
  role: UserRole!
  appliedJobs: [Job!]
  ownedJobs: [Job!]
}

input SignupInput {
  name: String!
  email: String!
  password: String!
  role: UserRole!
}

input LoginInput {
  email: String!
  password: String!
}

type Meta {
  hasMore: Boolean!
  nextCursor: ID
}

type JobConnectionResponse {
  data: [Job!]!
  meta: Meta!
}

input JobConnectionInput {
  cursor: ID
  limit: Int
}

type Query {
  me: User
  ownedJobs(input: JobConnectionInput!): JobConnectionResponse!
  appliedJobs(input: JobConnectionInput!): JobConnectionResponse!
}

type Mutation {
  signup(input: SignupInput!): User!
  login(input: LoginInput!): User!
  logout: Boolean!
}
